name: JCore
version: 0.1.0
main: com.jerae.jcore.JCore
api-version: '1.21'
author: Jerae
description: A core plugin with various features.
commands:
  chatcolor:
    description: Change your chat color.
    usage: /chatcolor
    aliases: [cc, color]
  nick:
    description: Change your nickname.
    usage: /nick <nickname>
    aliases: [nickname]
    permission: jcore.nick
  rename:
    description: Rename the item in your hand.
    usage: /rename <name>
    permission: jcore.rename
permissions:
  jcore.rename:
    description: Allows using the /rename command.
    default: true
  jcore.rename.color:
    description: Allows using color codes in item names.
    default: op
  jcore.rename.hex:
    description: Allows using hex colors in item names.
    default: op
  jcore.rename.gradient:
    description: Allows using gradient colors in item names.
    default: op
  jcore.rename.format:
    description: Allows using formatting codes in item names.
    default: op
  jcore.nick:
    description: Allows using the /nick command.
    default: true
  jcore.nick.color:
    description: Allows using color codes in nicknames.
    default: op
  jcore.nick.hex:
    description: Allows using hex colors in nicknames.
    default: op
  jcore.nick.gradient:
    description: Allows using gradient colors in nicknames.
    default: op
  jcore.nick.format:
    description: Allows using formatting codes in nicknames.
    default: op
  jcore.chatcolor.gui:
    description: Allows opening the chatcolor GUI.
    default: true
  jcore.chatcolor.hex:
    description: Allows using hex colors.
    default: op
  jcore.chatcolor.gradient:
    description: Allows using gradient colors.
    default: op
  jcore.chatcolor.format:
    description: Allows using formatting codes in chat.
    default: op
  jcore.chatcolor.color.*:
    description: Allows using all vanilla colors.
    default: op
    children:
      jcore.chatcolor.color.black: true
      jcore.chatcolor.color.dark_blue: true
      jcore.chatcolor.color.dark_green: true
      jcore.chatcolor.color.dark_aqua: true
      jcore.chatcolor.color.dark_red: true
      jcore.chatcolor.color.dark_purple: true
      jcore.chatcolor.color.gold: true
      jcore.chatcolor.color.gray: true
      jcore.chatcolor.color.dark_gray: true
      jcore.chatcolor.color.blue: true
      jcore.chatcolor.color.green: true
      jcore.chatcolor.color.aqua: true
      jcore.chatcolor.color.red: true
      jcore.chatcolor.color.light_purple: true
      jcore.chatcolor.color.yellow: true
      jcore.chatcolor.color.white: true
  jcore.chatcolor.color.black:
    description: Allows using the color black.
    default: op
  jcore.chatcolor.color.dark_blue:
    description: Allows using the color dark_blue.
    default: op
  jcore.chatcolor.color.dark_green:
    description: Allows using the color dark_green.
    default: op
  jcore.chatcolor.color.dark_aqua:
    description: Allows using the color dark_aqua.
    default: op
  jcore.chatcolor.color.dark_red:
    description: Allows using the color dark_red.
    default: op
  jcore.chatcolor.color.dark_purple:
    description: Allows using the color dark_purple.
    default: op
  jcore.chatcolor.color.gold:
    description: Allows using the color gold.
    default: op
  jcore.chatcolor.color.gray:
    description: Allows using the color gray.
    default: op
  jcore.chatcolor.color.dark_gray:
    description: Allows using the color dark_gray.
    default: op
  jcore.chatcolor.color.blue:
    description: Allows using the color blue.
    default: op
  jcore.chatcolor.color.green:
    description: Allows using the color green.
    default: op
  jcore.chatcolor.color.aqua:
    description: Allows using the color aqua.
    default: op
  jcore.chatcolor.color.red:
    description: Allows using the color red.
    default: op
  jcore.chatcolor.color.light_purple:
    description: Allows using the color light_purple.
    default: op
  jcore.chatcolor.color.yellow:
    description: Allows using the color yellow.
    default: op
  jcore.chatcolor.color.white:
    description: Allows using the color white.
    default: op