name: JCore
version: 0.1.0
main: com.jerae.jcore.JCore
api-version: '1.21'
author: Jerae
description: A core plugin with various features.
commands:
  chatcolor:
    description: Change your chat color.
    usage: /chatcolor
    aliases: [cc, color]
permissions:
  jcore.chatcolor.gui:
    description: Allows opening the chatcolor GUI.
    default: true
  jcore.chatcolor.hex:
    description: Allows using hex colors.
    default: op
  jcore.chatcolor.gradient:
    description: Allows using gradient colors.
    default: op
  jcore.chatcolor.vanilla.*:
    description: Allows using all vanilla colors.
    default: op
    children:
      jcore.chatcolor.vanilla.black: true
      jcore.chatcolor.vanilla.dark_blue: true
      jcore.chatcolor.vanilla.dark_green: true
      jcore.chatcolor.vanilla.dark_aqua: true
      jcore.chatcolor.vanilla.dark_red: true
      jcore.chatcolor.vanilla.dark_purple: true
      jcore.chatcolor.vanilla.gold: true
      jcore.chatcolor.vanilla.gray: true
      jcore.chatcolor.vanilla.dark_gray: true
      jcore.chatcolor.vanilla.blue: true
      jcore.chatcolor.vanilla.green: true
      jcore.chatcolor.vanilla.aqua: true
      jcore.chatcolor.vanilla.red: true
      jcore.chatcolor.vanilla.light_purple: true
      jcore.chatcolor.vanilla.yellow: true
      jcore.chatcolor.vanilla.white: true
  jcore.chatcolor.vanilla.black:
    description: Allows using the color black.
    default: true
  jcore.chatcolor.vanilla.dark_blue:
    description: Allows using the color dark_blue.
    default: true
  jcore.chatcolor.vanilla.dark_green:
    description: Allows using the color dark_green.
    default: true
  jcore.chatcolor.vanilla.dark_aqua:
    description: Allows using the color dark_aqua.
    default: true
  jcore.chatcolor.vanilla.dark_red:
    description: Allows using the color dark_red.
    default: true
  jcore.chatcolor.vanilla.dark_purple:
    description: Allows using the color dark_purple.
    default: true
  jcore.chatcolor.vanilla.gold:
    description: Allows using the color gold.
    default: true
  jcore.chatcolor.vanilla.gray:
    description: Allows using the color gray.
    default: true
  jcore.chatcolor.vanilla.dark_gray:
    description: Allows using the color dark_gray.
    default: true
  jcore.chatcolor.vanilla.blue:
    description: Allows using the color blue.
    default: true
  jcore.chatcolor.vanilla.green:
    description: Allows using the color green.
    default: true
  jcore.chatcolor.vanilla.aqua:
    description: Allows using the color aqua.
    default: true
  jcore.chatcolor.vanilla.red:
    description: Allows using the color red.
    default: true
  jcore.chatcolor.vanilla.light_purple:
    description: Allows using the color light_purple.
    default: true
  jcore.chatcolor.vanilla.yellow:
    description: Allows using the color yellow.
    default: true
  jcore.chatcolor.vanilla.white:
    description: Allows using the color white.
    default: true